version: '2'

services:
  rhel9: &rhel
    image: dalibo/buildpack-pkg:rockylinux9
    working_dir: /workspace
    environment:
    - VERSION
    - HISTFILE=/workspace/packaging/rpm/.docker-bash-history
    volumes:
    - ../../:/workspace
    entrypoint: ["/usr/local/sbin/tini"]
    command: /workspace/packaging/rpm/build.sh

  rhel8:
    <<: *rhel
    image: dalibo/buildpack-pkg:rockylinux8

  rhel7:
    <<: *rhel
    image: dalibo/buildpack-pkg:centos7
