site_name: temBoard
site_description: PostgreSQL Remote Control
site_author: www.dalibo.com
copyright: Copyright 2015-2020 <a href="http://www.dalibo.com">dalibo</a>
repo_url: https://github.com/dalibo/temboard/
theme:
  name: readthedocs
nav:
- Home: index.md
- Changelog: CHANGELOG.md
- Docker Quick Start: QUICKSTART.md
- Installation: installation.md
- Configuration: configuration.md
- Upgrade:
  - Upgrade 4 to 5 (RHEL/CentOS): temboard-upgrade-4-5.md
  - Upgrade 3.0 to 4.0 (RHEL/CentOS): temboard-upgrade-3.0-4.0.md
  - Upgrade 2.X to 3.0 (RHEL/CentOS): temboard-upgrade-2-3.0.md
  - Upgrade 1.2 to 2.0 (RHEL/CentOS): temboard-upgrade-1.2-2.0.md
  - Upgrade 1.1 to 1.2 (RHEL/CentOS): temboard-upgrade-1.1-1.2.md
  - Upgrade 0.0.1 to 1.1 (RHEL/CentOS): temboard-upgrade-0.0.1-1.1.md
- How To:
  - temBoard UI howto: temboard-howto.md
  - Alerting: temboard-howto-alerting.md
  - Maintenance: temboard-howto-maintenance.md
  - Statements: temboard-howto-statements.md

# Markdown settings
strict: yes
markdown_extensions:
- admonition
- fenced_code
- extra
- meta
- tables
- toc:
    baselevel: 2
    permalink: yes
