site_dir: dev/build/docs
site_name: temBoard
site_description: PostgreSQL Remote Control
site_author: www.dalibo.com
copyright: Copyright 2015-2022 <a href="http://www.dalibo.com">dalibo</a>
repo_url: https://github.com/dalibo/temboard/
theme:
  name: readthedocs
nav:
- Home: index.md
- Quick Start: quickstart.md
- Install:
  - Install the server: server_install.md
  - Install the agent: agent_install.md
  - Configure the server: server_configure.md
  - Configure the agent: agent_configure.md
- Upgrade:
  - Changelog: CHANGELOG.md
  - Upgrade the server: server_upgrade.md
  - Upgrade the agent: agent_upgrade.md
- How To:
  - temBoard UI howto: temboard-howto.md
  - Alerting: temboard-howto-alerting.md
  - Maintenance: temboard-howto-maintenance.md
  - Statements: temboard-howto-statements.md
  - Upgrade PostgreSQL: postgres_upgrade.md
  - temBoard performances: howto-temboard-performances.md
- Develop:
  - Contributing: CONTRIBUTING.md
  - Alerting internals: alerting.md
  - Agent REST API: agent_api.md


# Markdown settings
strict: yes
markdown_extensions:
- admonition
- fenced_code
- extra
- meta
- tables
- toc:
    baselevel: 2
    permalink: yes
