version: '2'

services:
  bookworm: &mkdeb
    image: dalibo/buildpack-pkg:bookworm
    environment:
      # See dch(1)
      DEBFULLNAME: ${DEBFULLNAME}
      DEBEMAIL: ${DEBEMAIL}
    volumes:
    - ../..:/workspace
    - ../../dist/:/dist
    command: /workspace/packaging/deb/mkdeb.sh

  bullseye:
    <<: *mkdeb
    image: dalibo/buildpack-pkg:bullseye

  buster:
    <<: *mkdeb
    image: dalibo/buildpack-pkg:buster

  stretch:
    <<: *mkdeb
    image: dalibo/buildpack-pkg:stretch
